version: '2.24.4'
name: robot_setup
services:
  taxim:
    build:
      context: .
    # stdin_open: true
    # The lines needed to deploy grapical application are marked as 1 
    environment:
      # - DISPLAY=:0 
        # XAUTHORITY:/root/.Xauthority
        #1
        DISPLAY: $DISPLAY
        QT_X11_NO_MITSHM: '1'
        NVIDIA_VISIBLE_DEVICES: all
        NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
    privileged: true
        #1
    volumes:
      #1
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/tejas/.Xauthority:/root/.Xauthority
      - ./code:/app/code
      - ./tutorial:/app/tutorial
    tty: true
    stdin_open: true
    network_mode: host
      #1  
    #1=to allow docker container graphical capability
    command: bash -c "tail -f /dev/null"