version: '2.24.4'
name: robot_setup
services:
  taxim:
    build:
      context: .
    # stdin_open: true
    # The lines needed to deploy grapical application are marked as 1 
    environment:
      # - DISPLAY=:0 
        # XAUTHORITY:/root/.Xauthority
        #1
        DISPLAY: $DISPLAY
        QT_X11_NO_MITSHM: '1'
        NVIDIA_VISIBLE_DEVICES: all
        NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
    privileged: true
        #1
    volumes:
      #1
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/tejas/.Xauthority:/root/.Xauthority
      - ./code:/app/code
      - ./tacto_setup:/app/tacto_setup
      - ./taxim_setup:/app/taxim_setup
      - ./tutorial:/app/tutorial
      - /home/tejas/projects/bullet3:/app/bullet3
      - ./taxim_test/taxim_copy:/app/Taxim      
      - /home/tejas/projects/egad_train_set:/app/egadtrainset
      - /home/tejas/projects/tactile_images:/app/tactile_images
      - /home/tejas/projects/taxim_robot_test/Taxim:/app/Taxim2  
      - /home/tejas/projects/Taxim:/app/Taxim_marker_sim  
      # - $HOME/workspace/egad_train_set:/app/egadtrainset
      # - $HOME/workspace/tactile_images:/app/tactile_images
    tty: true
    stdin_open: true
    network_mode: host
      #1  
    #1=to allow docker container graphical capability
    command: bash -c "cd /app/taxim_setup;tail -f /dev/null"
    #python multiThreading.py;